import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { createAdminClient } from '@/lib/supabase/admin'
import { ListingPageV2 } from '@/components/listing-pages/ListingPageV2'
import { ListingPageV2Inputs } from '@/lib/validations/listing-page-v2'

export const dynamic = 'force-dynamic'

const PHOTOS_BUCKET = 'listing-page-photos'

// Per-listing OG + <title> metadata so iMessage / Slack / Twitter /
// SMS link previews show the address and the hero photo instead of
// the generic "BT Investments" pulled from the root layout. Apple's
// link preview cache is aggressive — old shared links may keep
// showing the previous preview for a while.
export async function generateMetadata(
  { params }: { params: Promise<{ slug: string }> },
): Promise<Metadata> {
  const { slug } = await params

  const supabase = createAdminClient()
  const { data } = await supabase
    .from('listing_pages')
    .select('address, style_id, inputs')
    .eq('slug', slug)
    .eq('page_type', 'webpage')
    .eq('is_active', true)
    .single()

  if (!data) return { title: 'BT Investments' }

  const address = (data.address as string) ?? 'Listing'
  const title = address

  let imageUrl: string | undefined
  let description: string | undefined

  if (data.style_id === 'listing-page-v2') {
    const inputs = (data.inputs ?? {}) as Record<string, unknown>
    const heroPath = (inputs.heroPhotoPath as string | undefined) ?? (inputs.frontPhotoPath as string | undefined)
    if (heroPath) {
      const admin = createAdminClient()
      imageUrl = admin.storage.from(PHOTOS_BUCKET).getPublicUrl(heroPath).data.publicUrl
    }
    description = (inputs.customSubtitle as string | undefined) ?? undefined
  }

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url: `https://btinvestments.co/deals/${slug}`,
      siteName: 'BT Investments',
      images: imageUrl ? [{ url: imageUrl, alt: address }] : undefined,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: imageUrl ? [imageUrl] : undefined,
    },
  }
}

// Public listing-page route (the URL Randy shares with investors).
// Reachable from btinvestments.co without auth. Admin client bypasses
// RLS because this is the public marketing view of the flyer.
export default async function DealPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params

  const supabase = createAdminClient()
  const { data, error } = await supabase
    .from('listing_pages')
    .select('address, html_content, style_id, inputs')
    .eq('slug', slug)
    .eq('page_type', 'webpage')
    .eq('is_active', true)
    .single()

  if (error || !data) notFound()

  if (data.style_id === 'listing-page-v2') {
    const parsed = ListingPageV2Inputs.safeParse(data.inputs)
    if (!parsed.success) notFound()
    return <ListingPageV2 inputs={parsed.data} />
  }

  // v1 listings are full HTML documents (generated by GPT-4o into a
  // template). Render them inside an isolating iframe so their <html>,
  // <head>, and inline <style> don't conflict with the Next.js app
  // shell. Matches the pattern already used in HtmlViewerClient.
  return (
    <iframe
      srcDoc={data.html_content as string}
      sandbox="allow-same-origin allow-popups"
      title={(data.address as string) ?? 'Listing'}
      style={{
        position: 'fixed',
        inset: 0,
        width: '100%',
        height: '100%',
        border: 0,
      }}
    />
  )
}
