import { notFound } from 'next/navigation'
import { createAdminClient } from '@/lib/supabase/admin'
import { ListingPageV2 } from '@/components/listing-pages/ListingPageV2'
import { ListingPageV2Inputs } from '@/lib/validations/listing-page-v2'

export const dynamic = 'force-dynamic'

// Public listing-page route (the URL Randy shares with investors).
// Reachable from btinvestments.co without auth. Admin client bypasses
// RLS because this is the public marketing view of the flyer.
export default async function DealPage({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params

  const supabase = createAdminClient()
  const { data, error } = await supabase
    .from('listing_pages')
    .select('address, html_content, style_id, inputs')
    .eq('slug', slug)
    .eq('page_type', 'webpage')
    .eq('is_active', true)
    .single()

  if (error || !data) notFound()

  if (data.style_id === 'listing-page-v2') {
    const parsed = ListingPageV2Inputs.safeParse(data.inputs)
    if (!parsed.success) notFound()
    return <ListingPageV2 inputs={parsed.data} />
  }

  // v1 listings are full HTML documents (generated by GPT-4o into a
  // template). Render them inside an isolating iframe so their <html>,
  // <head>, and inline <style> don't conflict with the Next.js app
  // shell. Matches the pattern already used in HtmlViewerClient.
  return (
    <iframe
      srcDoc={data.html_content as string}
      sandbox="allow-same-origin allow-popups"
      title={(data.address as string) ?? 'Listing'}
      style={{
        position: 'fixed',
        inset: 0,
        width: '100%',
        height: '100%',
        border: 0,
      }}
    />
  )
}
